version: '2'
services:
  mesadas-server:
    build: .
    volumes:
      - ./:/app    
    ports:
      - "${PORT}:8000"            
    command: "yarn start"
    env_file:
      - .env    
    tty: true
    stdin_open: true